### ISSUE TITLE
[FR]: Guldborgsund please

### ISSUE THREAD

**Issue by Mareckil** [briis/affalddk#28] opened 2024-03-11 23:43 UTC
### Describe the feature you wish to make a request for

As mentioned above

**Comment by briis** [comment] 2024-03-12 05:59
Beklager. Guldborgsund bruger en virksomhed der hedder Refa til at styre dette. Jeg tjekkede lige lidt op på hvordan de leverer data og bliver ramt af at skulle indtaste MitID for at kunne få tømningsdata for en adresse, så det kan desværre ikke lade sig gøre.

**Comment by Mareckil** [comment] 2024-03-13 22:22
Hi there is mobile app Perfect Waste and it doesn't need MitID identification. I can setup any address and get information about collection dates.

**Comment by briis** [comment] 2024-03-23 11:36
Fine, but the issue is still there. Perfect Waste uses a different API than I currently support, so I first need to figure out how to extract data (If possible) from that API. I will leave this open as a feature request, and look at it as soon as possible.

**Comment by briis** [comment] 2024-03-31 09:11
It might be possible if somebody could look at how the Perfect Waste mobile app's pull out data, but I don't have the skills to do that. So I will have to close this for now, and then hopefully one day, someone can reverse engineer one of the APP's to see how they get data.

**Closed by briis** 2024-03-31 09:11 UTC
Labels: feature request, can't/wontfix
